name: pdui_flutter
description: "A SDUI library for the brave"
version: 0.0.3
repository: https://github.com/victorpigmeo/PDUI
homepage: https://github.com/victorpigmeo/PDUI

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  protobuf: ^5.0.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

license: "MIT"

# The following section is specific to Flutter packages.
flutter:

